-- AlterTable
ALTER TABLE `Question` MODIFY `category` ENUM('BASIC_THEORY', 'BASIC_KNOWLEDGE', 'BASIC_SKILL', 'INFECTION_KNOWLEDGE', 'PUBLIC', 'TRADITIONAL_CHINESE') NOT NULL,
    MODIFY `infectionTag` ENUM('HAND_HYGIENE', 'MEDICAL_WASTE', 'EXPOSURE', 'DISINFECTION', 'ISOLATION', 'STERILIZATION', 'MDRO', 'AIR_QUALITY') NULL;
